import org.eclipse.paho.client.mqttv3.MqttMessage

fun main()
{
    val listener: DeviceListener = DeviceListener(null)
    val payload = "[\n" +
            "   {\n" +
            "      \"ieee_address\":\"0x00158d00018255df\",\n" +
            "      \"type\":\"Router\",\n" +
            "      \"network_address\":29159,\n" +
            "      \"supported\":true,\n" +
            "      \"friendly_name\":\"my_plug\",\n" +
            "      \"endpoints\":{\n" +
            "         \"1\":{\n" +
            "            \"bindings\":[\n" +
            "               \n" +
            "            ],\n" +
            "            \"configured_reportings\":[\n" +
            "               \n" +
            "            ],\n" +
            "            \"clusters\":{\n" +
            "               \"input\":[\n" +
            "                  \"genOnOff\",\n" +
            "                  \"genBasic\"\n" +
            "               ],\n" +
            "               \"output\":[\n" +
            "                  \n" +
            "               ]\n" +
            "            }\n" +
            "         }\n" +
            "      },\n" +
            "      \"definition\":{\n" +
            "         \"model\":\"ZNCZ02LM\",\n" +
            "         \"vendor\":\"Xiaomi\",\n" +
            "         \"description\":\"Mi power plug ZigBee\"\n" +
            "      },\n" +
            "      \"power_source\":\"Mains (single phase)\",\n" +
            "      \"date_code\":\"02-28-2017\",\n" +
            "      \"model_id\":\"lumi.plug\",\n" +
            "      \"interviewing\":false,\n" +
            "      \"interview_completed\":true\n" +
            "   },\n" +
            "   {\n" +
            "      \"ieee_address\":\"0x90fd9ffffe6494fc\",\n" +
            "      \"type\":\"Router\",\n" +
            "      \"network_address\":57440,\n" +
            "      \"supported\":true,\n" +
            "      \"friendly_name\":\"my_bulb\",\n" +
            "      \"endpoints\":{\n" +
            "         \"1\":{\n" +
            "            \"bindings\":[\n" +
            "               \n" +
            "            ],\n" +
            "            \"configured_reportings\":[\n" +
            "               \n" +
            "            ],\n" +
            "            \"clusters\":{\n" +
            "               \"input\":[\n" +
            "                  \"genOnOff\",\n" +
            "                  \"genBasic\",\n" +
            "                  \"genLevelCtrl\"\n" +
            "               ],\n" +
            "               \"output\":[\n" +
            "                  \"genOta\"\n" +
            "               ]\n" +
            "            }\n" +
            "         }\n" +
            "      },\n" +
            "      \"definition\":{\n" +
            "         \"model\":\"LED1624G9\",\n" +
            "         \"vendor\":\"IKEA\",\n" +
            "         \"description\":\"TRADFRI LED bulb E14/E26/E27 600 lumen, dimmable, color, opal white\",\n" +
            "         \"exposes\":[\n" +
            "            {\n" +
            "               \"type\":\"light\",\n" +
            "               \"features\":[\n" +
            "                  \"state\",\n" +
            "                  \"brightness\",\n" +
            "                  \"color_xy\"\n" +
            "               ]\n" +
            "            }\n" +
            "         ]\n" +
            "      },\n" +
            "      \"power_source\":\"Mains (single phase)\",\n" +
            "      \"software_build_id\":\"1.3.009\",\n" +
            "      \"model_id\":\"TRADFRI bulb E27 CWS opal 600lm\",\n" +
            "      \"date_code\":\"20180410\",\n" +
            "      \"interviewing\":false,\n" +
            "      \"interview_completed\":true\n" +
            "   },\n" +
            "   {\n" +
            "      \"ieee_address\":\"0x00169a00022256da\",\n" +
            "      \"type\":\"Router\",\n" +
            "      \"endpoints\":{\n" +
            "         \"1\":{\n" +
            "            \"bindings\":[\n" +
            "               {\n" +
            "                  \"cluster\":\"genOnOff\",\n" +
            "                  \"target\":{\n" +
            "                     \"type\":\"endpoint\",\n" +
            "                     \"endpoint\":1,\n" +
            "                     \"ieee_address\":\"0x000b57fffec6a5b3\"\n" +
            "                  }\n" +
            "               },\n" +
            "               {\n" +
            "                  \"cluster\":\"genOnOff\",\n" +
            "                  \"target\":{\n" +
            "                     \"type\":\"group\",\n" +
            "                     \"id\":1\n" +
            "                  }\n" +
            "               }\n" +
            "            ],\n" +
            "            \"configured_reportings\":[\n" +
            "               {\n" +
            "                  \"cluster\":\"genOnOff\",\n" +
            "                  \"attribute\":\"onOff\",\n" +
            "                  \"maximum_report_interval\":10,\n" +
            "                  \"minimum_report_interval\":1,\n" +
            "                  \"reportable_change\":1\n" +
            "               }\n" +
            "            ],\n" +
            "            \"clusters\":{\n" +
            "               \"input\":[\n" +
            "                  \"genBasic\",\n" +
            "                  \"msIlluminanceMeasurement\"\n" +
            "               ],\n" +
            "               \"output\":[\n" +
            "                  \"genOnOff\"\n" +
            "               ]\n" +
            "            }\n" +
            "         }\n" +
            "      },\n" +
            "      \"network_address\":22160,\n" +
            "      \"supported\":false,\n" +
            "      \"friendly_name\":\"my_sensor\",\n" +
            "      \"definition\":null,\n" +
            "      \"power_source\":\"Battery\",\n" +
            "      \"date_code\":\"04-28-2019\",\n" +
            "      \"model_id\":null,\n" +
            "      \"interviewing\":false,\n" +
            "      \"interview_completed\":true\n" +
            "   },\n" +
            "   {\n" +
            "      \"ieee_address\":\"0x00124b00120144ae\",\n" +
            "      \"type\":\"Coordinator\",\n" +
            "      \"network_address\":0,\n" +
            "      \"supported\":false,\n" +
            "      \"endpoints\":{\n" +
            "         \"1\":{\n" +
            "            \"bindings\":[\n" +
            "               \n" +
            "            ],\n" +
            "            \"configured_reportings\":[\n" +
            "               \n" +
            "            ],\n" +
            "            \"clusters\":{\n" +
            "               \"input\":[\n" +
            "                  \n" +
            "               ],\n" +
            "               \"output\":[\n" +
            "                  \n" +
            "               ]\n" +
            "            }\n" +
            "         }\n" +
            "      },\n" +
            "      \"friendly_name\":\"Coordinator\",\n" +
            "      \"definition\":null,\n" +
            "      \"power_source\":null,\n" +
            "      \"date_code\":null,\n" +
            "      \"model_id\":null,\n" +
            "      \"interviewing\":false,\n" +
            "      \"interview_completed\":true\n" +
            "   }\n" +
            "]"
    val message: MqttMessage = MqttMessage(payload.toByteArray())
    listener.messageArrived(null, message)
}